### ISSUE TITLE
running it with GC-0010 erro

### ISSUE THREAD

**Issue by redrobotdev** [pierre-haessig/pycozir#1]
when running like so:

`python3 cozir_test.py
`
I get the following error:

```
connected to "/dev/ttyUSB0"
set operating mode to "polling"
Traceback (most recent call last):
  File "cozir_test.py", line 2, in <module>
    c = Cozir('/dev/ttyUSB0')
  File "/usr/local/lib/python3.5/dist-packages/PyCOZIR-0.1-py3.5.egg/cozir/cozir.py", line 48, in __init__
  File "/usr/local/lib/python3.5/dist-packages/PyCOZIR-0.1-py3.5.egg/cozir/cozir.py", line 113, in set_mode

```

**Comment by pierre-haessig** [comment]
Hello,
Is this the complete error traceback, because I don't see the actual error?

Also, what is GC-0010?

**Comment by redrobotdev** [comment]
I apologize my mistake, I connected the pins in reverse the library works beautifully.
